Features and dependencies can't have the same name
The document was describing a Cargo.toml containing
```
[dependencies]
postgres = { version = "*", optional = true }
postgres-macros = { version = "*", optional = true }

[features]
postgres = ["postgres", "postgres-macros"]
```

If you tried doing this you'd get an error:
```
error: failed to parse manifest at `/home/jonathan/tmp/features/Cargo.toml`

Caused by:
  Features and dependencies cannot have the same name: `postgres`
```